name: coop_case
description: "Case project for coop."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  provider: ^6.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0
  mockito: ^5.4.2
  test: ^1.24.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/coop.png

  